# Generated by Django 5.0.6 on 2024-06-09 13:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('d6f611ae-e265-4713-ad5c-4d24f9e947e7'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('0edbca04-7033-4f24-b567-c797cff05afc'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('f75b3487-a940-4225-8d61-80b1bdf66ef4'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.UUID('e2cdbd56-b7a9-4e28-8741-eca21e81a8a0'), editable=False, unique=True),
        ),
    ]
